"""Prompt Builder for the Smart Grid LLM Investigation module.

Constructs system and user prompts that enforce:
1. Grounding strictly in Digital Twin evidence.
2. Clear separation: OBSERVATIONS != HYPOTHESES.
3. No hallucination of measurements, breaker states, or attack certainty.
4. Strict JSON output adhering to LLMInvestigationOutput schema.
"""

from __future__ import annotations

import json
from typing import Dict, List, Optional, Union

from src.digital_twin.schemas import DigitalTwinOutput
from src.llm.schemas import LLMInvestigationInput


class PromptBuilder:
    """Builds structured system and user prompts for Smart Grid LLM investigation."""

    SYSTEM_PROMPT = (
        "You are a Smart Grid event investigation assistant.\n\n"
        "You receive structured evidence generated by a deterministic Digital Twin and ML-based anomaly detection pipeline.\n\n"
        "Your job is to explain the observed event using only the supplied evidence.\n\n"
        "Do not invent measurements, topology states, breaker states, or events.\n\n"
        "Do not claim that an event is definitely a cyberattack.\n\n"
        "When cyber-related explanations are possible, describe them as hypotheses rather than facts.\n\n"
        "Separate observed evidence from interpretation.\n\n"
        "If the evidence is insufficient, explicitly state that the cause cannot be determined."
    )

    JSON_SCHEMA_INSTRUCTIONS = """
Respond with a single valid JSON object strictly matching this schema:
{
  "event_summary": "<Concise 1-2 sentence description of what occurred>",
  "anomaly_assessment": {
    "detected": <true or false>,
    "severity": "<NONE, LOW, MODERATE, HIGH, or CRITICAL>",
    "fusion_score": <float>
  },
  "observed_evidence": [
    "<Direct factual statement from the Digital Twin evidence>",
    "<Do NOT include speculative attack conclusions here>"
  ],
  "grid_state": {
    "topology_state": "<e.g. ALL_LINES_IN_SERVICE, LINE_1_OUTAGE, etc.>",
    "affected_components": ["<list of affected lines/buses/relays>"],
    "breaker_states": {
      "<breaker_id>": "<OPEN or CLOSED>"
    }
  },
  "physical_assessment": {
    "physical_consistency": "<consistent, inconsistent, or unknown>",
    "topology_consistency": "<consistent, inconsistent, or unknown>",
    "measurement_consistency": "<consistent, inconsistent, or unknown>"
  },
  "possible_explanations": [
    {
      "hypothesis": "<Plausible physical or cyber-physical explanation>",
      "reasoning": "<Explanation of why this hypothesis is plausible based on the evidence>",
      "confidence": <float between 0.0 and 1.0>
    }
  ],
  "recommended_investigation": [
    "<Specific concrete action for control room or forensic engineers>"
  ],
  "limitations": [
    "<Specific data limitation, missing telemetry, or observation boundary>"
  ]
}

CRITICAL RULES:
1. OBSERVATIONS != HYPOTHESES: The "observed_evidence" list must contain ONLY factual observations reported by the Digital Twin. Speculative interpretations belong solely in "possible_explanations".
2. ZERO HALLUCINATION: Never invent sensor values, breaker commands, attacker identities, or timestamps not provided in the input.
3. NO CERTAINTY CLAIMS: Never state that an event is definitely a cyberattack; use hypothesis framing.
4. VALID JSON ONLY: Do not output any explanation, markdown code fences, or reasoning text outside the JSON object.
"""

    def build_system_prompt(self) -> str:
        """Returns the standardized system prompt."""
        return self.SYSTEM_PROMPT

    def build_user_prompt(self, dt_input: Union[LLMInvestigationInput, DigitalTwinOutput, Dict]) -> str:
        """Constructs the user prompt containing the structured Digital Twin evidence."""
        if isinstance(dt_input, DigitalTwinOutput):
            inp = LLMInvestigationInput.from_digital_twin_output(dt_input)
        elif isinstance(dt_input, dict) and "grid_state" in dt_input:
            # Reconstruct from dict
            dt_obj = DigitalTwinOutput(
                timestamp=str(dt_input.get("timestamp", "0")),
                grid_state=dt_input.get("grid_state", {}),
                anomaly_evidence=dt_input.get("anomaly_evidence", {}),
                physical_analysis=dt_input.get("physical_analysis", {}),
                component_states=dt_input.get("component_states", {}),
                investigation=dt_input.get("investigation", {}),
                evidence=dt_input.get("evidence", []),
            )
            inp = LLMInvestigationInput.from_digital_twin_output(dt_obj)
        elif isinstance(dt_input, LLMInvestigationInput):
            inp = dt_input
        else:
            raise TypeError(f"Unsupported input type for prompt builder: {type(dt_input)}")

        evidence_context = inp.to_prompt_context()

        user_prompt = (
            "Analyze the following Smart Grid Digital Twin output and provide an investigation report:\n\n"
            "==================== DIGITAL TWIN EVIDENCE ====================\n"
            f"{evidence_context}\n"
            "===============================================================\n\n"
            f"{self.JSON_SCHEMA_INSTRUCTIONS}"
        )
        return user_prompt
